# see: https://github.com/probot/settings

repository:
  name: github.action.sqitch
  description: GitHub custom action for running Sqitch mogrations
  topics: github action sqitch
  private: false
  has_issues: false
  has_wiki: false
  is_template: false
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  archived: false

teams:
  - name: engineering
    permission: admin

branches:
  - name: main
    protection:
      required_conversation_resolution: true
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      restrictions:
