# action.yml
name: 'Sqitch Action'
description: 'Run migrations'
inputs:
  command:
    description: 'Command to run'
    required: true
  target:
    description: 'Target'
    required: true

runs:
  using: 'docker'
  image: 'docker://sqitch/sqitch:v1.4'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.target }}
